title: nijaru
baseurl: ""
url: ""
# enforce_ssl: nijaru.com
description: Nick Russo's personal website and blog.

permalink: /posts/:title
redirects: yes

markdown: kramdown
highlighter: rouge

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
