# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Nick Russo
email: nijaru0x@example.com
description: >-
    My personal blog about programming, audio, and other things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nijaru.com"
twitter_username: nijaru0x
github_username: nijaru
back_home_text: Back

# Build settings
theme: no-style-please
plugins:
    - jekyll-feed

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
