name: Generate Resume PDF

on:
  push:
    branches:
      - main
    paths:
      - 'resume.json'
      - '.github/workflows/generate-resume-pdf.yml'
  workflow_dispatch:

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install JSON Resume CLI
        run: npm install -g resume-cli

      - name: Install JSON Resume theme
        run: npm install jsonresume-theme-elegant

      - name: Generate PDF from resume.json
        run: |
          # Generate PDF using JSON Resume with the elegant theme
          resume export public/Nicholas_Russo_Resume.pdf --format pdf --theme elegant

      - name: Commit PDF to repository
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/Nicholas_Russo_Resume.pdf
          git diff --staged --quiet || git commit -m "chore: auto-update resume PDF"
          git pull --rebase
          git push
